# Generated by Django 4.1.3 on 2022-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_phrase', models.CharField(max_length=200, verbose_name='Поисковая фраза')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регион')),
            ],
        ),
        migrations.AddConstraint(
            model_name='advertscounter',
            constraint=models.UniqueConstraint(fields=('search_phrase', 'region'), name='unique_pair'),
        ),
    ]
