# Generated by Django 4.1.3 on 2022-11-09 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checker_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='advertscounter',
            name='unique_pair',
        ),
        migrations.AddField(
            model_name='advertscounter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата создания запроса', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
