# Generated by Django 4.1.3 on 2022-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_api', '0002_remove_advertscounter_unique_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertscounter',
            name='counter',
            field=models.IntegerField(default=1, help_text='Количество объявлений', verbose_name='Количество объявлений'),
            preserve_default=False,
        ),
    ]
