# Generated by Django 4.1.3 on 2022-11-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_api', '0004_checkdate_remove_advertscounter_created_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advertscounter',
            constraint=models.UniqueConstraint(fields=('search_phrase', 'region'), name='unique_pair'),
        ),
    ]
