# Generated by Django 4.1.3 on 2022-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_api', '0005_advertscounter_unique_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertscounter',
            name='counter',
        ),
        migrations.AddField(
            model_name='checkdate',
            name='counter',
            field=models.IntegerField(default=234, help_text='Количество объявлений', verbose_name='Количество объявлений'),
            preserve_default=False,
        ),
    ]
